Repository FRONTENDBOOTCAMP-13th/JS-01-c1ass, pull requests merged in 2025-05, with the labels that each got.

#3 :sparkles: feat: index.html에 컴포넌트/페이지 링크 연결
  index.html
Labels: ✨Feature, ✔️Done

#6 Feature/clock widget
  index.html
  public/asserts/clock-widget/center.svg
  public/asserts/clock-widget/hour-niddle.svg
  public/asserts/clock-widget/minute-niddle.svg
  public/asserts/clock-widget/pan.svg
  public/asserts/clock-widget/second-niddle.svg
  src/components/clock-widget.html
  src/ts/clock-widget.ts
Labels: ✨Feature, ✔️Done

#7 :sparkles: feat: clock-widget에 그림자 추가
  src/components/clock-widget.html
Labels: ✨Feature, ✔️Done

#9 Feature/weather widget
  index.html
  public/asserts/weather-widget/clear.svg
  public/asserts/weather-widget/cloudy.svg
  public/asserts/weather-widget/location-arrow.svg
  public/asserts/weather-widget/partly_cloudy.svg
  public/asserts/weather-widget/rain.svg
  public/asserts/weather-widget/snow.svg
  public/asserts/weather-widget/windy.svg
  src/components/weather-widget.html
  src/ts/weather-widget.ts
Labels: ✨Feature, 🔨In Progress

#15 :sparkles: feat: mac-panel 컴포넌트 구현 / :lipstick: design: Pretendard 폰트 추가
  .gitignore
  index.html
  public/asserts/top-bar/apple-logo-black.svg
  public/asserts/top-bar/apple-logo-white.svg
  public/asserts/top-bar/battery-black.svg
  public/asserts/top-bar/battery-white.svg
  public/asserts/top-bar/search-black.svg
  public/asserts/top-bar/search-white.svg
  public/asserts/top-bar/toggle-black.svg
  public/asserts/top-bar/toggle-white.svg
  public/asserts/top-bar/wifi-black.svg
  public/asserts/top-bar/wifi-white.svg
  public/fonts/pretendard/pretendardvariable.css
  public/fonts/pretendard/woff2/PretendardVariable.woff2
  src/components/mac-panel.html
  src/style.css
  src/ts/mac-panel.ts
Labels: ✨Feature, ✔️Done

#16 feature: icon-bar 컴포넌트 구현
  index.html
  src/components/icon-bar.html
  src/main.ts
Labels: ✨Feature, ✔️Done

#17 feat: Calendar-widget 컴포넌트 구현
  src/components/calendar-widget.html
  src/ts/calendar-widget.ts
Labels: ✨Feature, ✔️Done

#23 feat: memo-widget 컴포넌트 구현 (및 calendar-widget 스타일 수정)
  index.html
  public/asserts/memo-widget/folder.svg
  src/components/calendar-widget.html
  src/components/memo-widget.html
Labels: ✨Feature, ✔️Done

#24 Feature/weather widget
  src/components/weather-widget.html
  src/ts/weather-widget.ts
Labels: ✨Feature, 🔨In Progress

#26 Feature/mac page
  index.html
  public/asserts/mac/apple-logo.webp
  public/asserts/mac/mac-screen-base-background-img.png
  src/pages/mac.html
  src/ts/mac-no-scroll.ts
  src/ts/mac-screen-size.ts
  src/ts/mac-setting.ts
Labels: ✨Feature, ✔️Done

#30 Feature/icon click
  src/pages/mac.html
  src/style.css
  src/ts/icon.ts
  src/ts/mac-panel-container.ts
  src/ts/mac-panel-manager.ts
  src/ts/mac-setting.ts
Labels: ✨Feature, ✔️Done, ✅Test

#33 Feature/icon class
  src/pages/mac.html
  src/style.css
  src/ts/icon.ts
  src/ts/mac-setting.ts
Labels: ✨Feature, ✔️Done, ✅Test

#38 Feature/mac bar button click
  src/pages/mac.html
  src/style.css
  src/ts/icon-bar.ts
  src/ts/icon.ts
  src/ts/mac-panel-container.ts
  src/ts/mac-panel-manager.ts
  src/ts/mac-panel.ts
  src/ts/mac-setting.ts
Labels: ✨Feature, ♻️Refactoring, ✔️Done, ✅Test

#40 :sparkles: feat: full screen이 될 때와 default screen이 될 때 transiton 구현
  src/ts/mac-panel-container.ts
Labels: ✨Feature, ✔️Done

#37 Feature/card
  index.html
  public/asserts/card/audio/banana.mp3
  public/asserts/card/audio/brr.mp3
  public/asserts/card/audio/card-draw.mp3
  public/asserts/card/audio/croco.mp3
  public/asserts/card/audio/ping.mp3
  public/asserts/card/audio/trala.mp3
  public/asserts/card/audio/tung.mp3
  public/asserts/card/img/card-back.svg
  public/asserts/card/img/card-bg.svg
  public/asserts/card/img/draw-button.svg
  public/asserts/card/img/left-click.svg
  public/asserts/card/img/n/bow.svg
  public/asserts/card/img/n/cane.svg
  public/asserts/card/img/n/dog.svg
  public/asserts/card/img/n/ghost.svg
  public/asserts/card/img/n/goblin.svg
  public/asserts/card/img/n/morning-star.svg
  public/asserts/card/img/n/mushroom.svg
  public/asserts/card/img/n/poo.svg
  public/asserts/card/img/n/rat.svg
  public/asserts/card/img/n/shield.svg
  public/asserts/card/img/n/snail.svg
  public/asserts/card/img/n/spear.svg
  public/asserts/card/img/n/spider.svg
  public/asserts/card/img/n/sword.svg
  public/asserts/card/img/n/wand.svg
  public/asserts/card/img/r/bear.svg
  public/asserts/card/img/r/dragon.svg
  public/asserts/card/img/r/ork.svg
  public/asserts/card/img/r/reaper.svg
  public/asserts/card/img/r/unicorn.svg
  public/asserts/card/img/sr/cinderella.svg
  public/asserts/card/img/sr/elsa.svg
  public/asserts/card/img/sr/ping.svg
  public/asserts/card/img/sr/princess.svg
  public/asserts/card/img/ssr/banana.svg
  public/asserts/card/img/ssr/brr.svg
  public/asserts/card/img/ssr/croco.svg
  public/asserts/card/img/ssr/trala.svg
  public/asserts/card/img/ssr/tung.svg
  public/asserts/card/img/ticket.svg
  src/pages/card.html
  src/style.css
  src/ts/card.ts
Labels: ✨Feature, 🔨In Progress

#48 💄 style: 카드게임 컬렉션 스타일 수정
  src/ts/card.ts
Labels: :lipstick:UI Improvement, ✔️Done

#49 calendar-widget에서 setTimeout으로 날짜 갱신 문제 수정 (테스트 미완료)
  src/ts/calendar-widget.ts
Labels: 🐛Bugfix, 🔨In Progress

#50 Feature/mac bar button
  public/asserts/mac/icon-test.png
  src/components/icon.html
  src/pages/mac.html
  src/style.css
  src/ts/icon-bar.ts
  src/ts/mac-panel-container.ts
  src/ts/mac-panel-manager.ts
  src/ts/mac-setting.ts
Labels: 🐛Bugfix, ✨Feature, ♻️Refactoring, ✔️Done

#55 :bug: fix: card 게임 접근성 문제, 컬렉션 모달 이미지 깜빡임 문제 수정
  src/pages/card.html
  src/ts/card.ts
Labels: 🐛Bugfix, ✔️Done, 👁️Accessibility

#58 :lion: chore: html 파일의 head에 폰트 추가
  index.html
  src/components/clock-widget.html
  src/components/icon-bar.html
  src/components/icon.html
  src/components/top-bar.html
  src/components/weather-widget.html
  src/pages/card.html
  src/pages/mac.html
Labels: ✔️Done, :whale:Chore

#59 Feature/card
  src/pages/card.html
  src/ts/card.ts
Labels: 🐛Bugfix, ✔️Done

#61 Refactor/doodi game
  index.html
  src/components/doodi-game/doodi-character.html
  src/components/doodi-game/doodi-gamepage.html
  src/components/doodi-game/doodi-interface.html
  src/pages/doodi-all.html
  src/pages/doodi-game.html
  src/style.css
  src/ts/doodi-game/doodi-animation.ts
  src/ts/doodi-game/doodi-mole.ts
  src/ts/doodi-game/doodi-screen.ts
  src/ts/doodi-game/doodi-timer.ts
  src/ts/doodi-game/doodi-typing.ts
  src/ts/mac-setting.ts
Labels: 🐛Bugfix, ✨Feature, :lipstick:UI Improvement, 🔨In Progress

#62 Feature/mac panel iframe
  index.html
  public/asserts/mac/arrow.png
  public/asserts/mac/card.png
  public/asserts/mac/doodi.png
  public/asserts/mac/notfound.png
  public/asserts/mac/socks.png
  src/pages/notfound.html
  src/programID.ts
  src/style.css
  src/ts/card.ts
  src/ts/icon-bar.ts
  src/ts/mac-panel-container.ts
  src/ts/mac-panel-manager.ts
  src/ts/mac-setting.ts
  vite.config.js
Labels: ✨Feature, ✔️Done

#64 :sparkles: feat: 위젯 드래그앤드롭 기능 구현
  src/pages/mac.html
  src/style.css
  src/ts/widget-move.ts
Labels: ✨Feature, 🔨In Progress

#63 :sparkles: feat: 화살피하기게임 구현 완료
  index.html
  src/pages/arrow-dodge-game.html
  src/style.css
  src/ts/arrow-dodge-game.ts
Labels: ✨Feature, ✔️Done

#66 :bug: fix: clock-widget 바늘 움직이는 로직을 변경해서 위젯을 움직일 때 바늘이 멈추는 현상 수정
  src/ts/clock-widget.ts
Labels: 🐛Bugfix, ✔️Done

#68 :bug: fix: doodi의 fileURL 변경
  src/programID.ts
Labels: 🐛Bugfix, ✔️Done

#70 :bug: fix: iframe 클릭 시 mac-panel이 최상단에 배치되지 않은 현상을 투명한 mac-panel-cover를 구현해서 수정
  src/style.css
  src/ts/mac-panel-container.ts
Labels: 🐛Bugfix, ✔️Done

#72 :lion: chore: program interface에 arrow-dodge 연결
  public/asserts/mac/arrow-dodge.png
  src/programID.ts
  src/ts/mac-setting.ts
Labels: ✔️Done, :whale:Chore

#75 Bugfix/move widget
  src/pages/mac.html
  src/ts/widget-move.ts
Labels: 🐛Bugfix, ✔️Done

#77 Feature/socks game 간단히 구현
  index.html
  public/asserts/socks-game/check.svg
  public/asserts/socks-game/img_gt.png
  public/asserts/socks-game/img_lt.png
  public/asserts/socks-game/label_404.png
  public/asserts/socks-game/logo_sockast.png
  public/asserts/socks-game/paper-sound.aac
  public/asserts/socks-game/paper1.png
  public/asserts/socks-game/paper2.png
  public/asserts/socks-game/paper3.png
  public/asserts/socks-game/paper_package.png
  public/asserts/socks-game/postBox.png
  public/asserts/socks-game/socks-list/socks1.png
  public/asserts/socks-game/socks-list/socks10.png
  public/asserts/socks-game/socks-list/socks2.png
  public/asserts/socks-game/socks-list/socks3.png
  public/asserts/socks-game/socks-list/socks4.png
  public/asserts/socks-game/socks-list/socks5.png
  public/asserts/socks-game/socks-list/socks6.png
  public/asserts/socks-game/socks-list/socks7.png
  public/asserts/socks-game/socks-list/socks8.png
  public/asserts/socks-game/socks-list/socks9.png
  public/asserts/socks-game/story.png
  public/asserts/socks-game/story_eng.png
  public/asserts/socks-game/story_kor.png
  src/pages/socks-game.html
  src/style.css
  src/ts/socks-game.ts
Labels: ✨Feature, ✔️Done

#79 :sparkles: feat: sockast를 vite, index, programID에 연결
  index.html
  src/programID.ts
  vite.config.js
Labels: ✨Feature, ✔️Done

#80 Refactor/doodi game 오류 수정
  src/ts/doodi-game/doodi-screen.ts
  src/ts/doodi-game/doodi-timer.ts
Labels: 🐛Bugfix, ✔️Done

#84 Feature/mac background div
  src/pages/mac.html
  src/ts/mac-setting.ts
Labels: ✨Feature, ✔️Done, ✅Test

#86 Chore/fix vite
  src/pages/doodi-all.html
  vite.config.js
Labels: ✔️Done, :whale:Chore

#93 :bug: fix: 불필요한 콘솔 로그 제거
  src/pages/arrow-dodge-game.html
  src/ts/arrow-dodge-game.ts
Labels: 🐛Bugfix, ✔️Done

#98 :white_check_mark: test: doodi-game 로딩화면 구현 및 이미지 프리로드 함수 테스트
  src/pages/doodi-all.html
  src/ts/doodi-game/doodi-load.ts
Labels: 🐛Bugfix, ✅Test

#101 Feature/calander widget click
  package-lock.json
  package.json
  src/pages/mac.html
  src/programID.ts
  src/style.css
  src/ts/mac-no-scroll.ts
  src/ts/mac-panel-container.ts
  src/ts/mac-panel-manager.ts
  src/ts/mac-setting.ts
  src/ts/widget-manager.ts
Labels: ✨Feature, ✔️Done, ✅Test

#106 :lion: chore: mac-bg 복원
  src/pages/mac.html
Labels: ✔️Done, :whale:Chore

#107 Refactor/doodi game 반응형으로 수정
  src/pages/doodi-all.html
  src/ts/doodi-game/doodi-animation.ts
  src/ts/doodi-game/doodi-mole.ts
  src/ts/doodi-game/doodi-screen.ts
Labels: 🐛Bugfix, ♻️Refactoring, :lipstick:UI Improvement, ✔️Done

#111 Feature/memo widget click
  src/pages/mac.html
  src/programID.ts
  src/ts/widget-manager.ts
Labels: ✨Feature, ✔️Done

#113 Chore/remove tiny code
  src/pages/mac.html
  src/ts/mac-setting.ts
  src/ts/widget-manager.ts
  src/ts/widget-move.ts
Labels: :whale:Chore

#121 :sparkles: feat: context-menu UI 구현
  index.html
  src/components/context-menu.html
  src/style.css
  vite.config.js
Labels: ✨Feature, ✔️Done

#120 :sparkles: feat: top-bar 사용자의 다크/라이트 모드에 반응하게 구현
  src/components/top-bar.html
  src/pages/mac.html
Labels: ✨Feature, :lipstick:UI Improvement, ✔️Done

#124 Feature/mac screen context menu
  src/pages/mac.html
  src/style.css
  src/ts/context-menu.ts
  src/ts/mac-setting.ts
Labels: ✔️Done

#126 :sparkles: feat: sortableJS library를 사용하여 아이콘을 드래그&드롭으로 위치를 조정하는 기능 구현
  package-lock.json
  package.json
  src/pages/mac.html
  src/ts/icon-move.ts
Labels: ✨Feature, ✔️Done

#130 :sparkles: feat: 배경화면 선택기능 구현
  public/asserts/bg-selector-img/butterfly.webp
  public/asserts/bg-selector-img/cloud.webp
  public/asserts/bg-selector-img/couple.webp
  public/asserts/bg-selector-img/flower.webp
  public/asserts/bg-selector-img/mountain.webp
  public/asserts/bg-selector-img/park.webp
  public/asserts/bg-selector-img/pond.webp
  public/asserts/bg-selector-img/sea.webp
  public/asserts/bg-selector-img/sunset.webp
  public/asserts/bg-selector-img/weat.webp
  src/pages/bg-selector.html
  src/ts/bg-selector.ts
Labels: ✨Feature, 🔨In Progress

#131 :lion: chore: mac 스크린 뒤 배경화면 추가
  public/asserts/mac/background-web/001.png
  public/asserts/mac/background-web/002.jpg
  public/asserts/mac/background-web/002.png
  public/asserts/mac/logo-pocketPC.png
  public/asserts/mac/pedestal.png
  public/asserts/mac/pedestal_black.png
  public/asserts/mac/pedestal_white.png
  public/asserts/mac/support.png
  src/pages/mac.html
Labels: ✔️Done, :whale:Chore

#132 :sparkles: feat: 우측 배경 포스트잇 추가
  src/pages/mac.html
  src/ts/mac-setting.ts
Labels: ✨Feature, ✅Test

#135 Chore/doodi game - 두더지 크기 수정
  src/pages/doodi-all.html
  src/ts/doodi-game/doodi-load.ts
  src/ts/doodi-game/doodi-mole.ts
Labels: ✔️Done, :whale:Chore

#136 :sparkles: feat: memo-widget을 클릭했을 때 mac-panel에서 보여줄 UI 구현
  index.html
  public/asserts/mac/add-memo-icon.svg
  public/asserts/mac/search-icon.svg
  src/components/memo-program.html
  src/style.css
  src/ts/widget-manager.ts
  vite.config.js
Labels: ✨Feature, ✔️Done

#134 Chore/mac 스크린 뒤 배경화면 다크모드 추가
  public/asserts/mac/background-web/001.png
  public/asserts/mac/background-web/002.jpg
  public/asserts/mac/background-web/002.png
  public/asserts/mac/background-web/bg-black.jpg
  public/asserts/mac/background-web/bg-black.webp
  public/asserts/mac/background-web/bg-white.jpg
  public/asserts/mac/background-web/bg-white.webp
  public/asserts/mac/pedestal_black.png
  public/asserts/mac/pedestal_black.webp
  public/asserts/mac/pedestal_white.png
  public/asserts/mac/pedestal_white.webp
  public/asserts/mac/support.png
  public/asserts/mac/support_black.webp
  public/asserts/mac/support_white.webp
  src/pages/mac.html
Labels: ✔️Done, :whale:Chore

#138 Bugfix/doodi game - 이미지 프리로드 수정 (+socks-game), mac 충돌 수정
  src/pages/mac.html
  src/pages/socks-game.html
  src/ts/doodi-game/doodi-load.ts
  src/ts/socks-game.ts
Labels: 🐛Bugfix, ✔️Done

#140 Refactor/calendar widget 시간 오류 수정
  src/ts/calendar-widget.ts
Labels: 🐛Bugfix, ✔️Done

#142 Feature/memo program
  src/components/memo-program.html
  src/style.css
  src/ts/widget-manager.ts
Labels: ✨Feature, ✔️Done

#144 :lion: chore: mac 배경화면 수정 및 mac-right-bg 안 보이게 설정
  public/asserts/mac/background-web/bg-black.jpg
  public/asserts/mac/background-web/bg-black.webp
  public/asserts/mac/background-web/bg-white.jpg
  public/asserts/mac/pedestal.png
  public/asserts/mac/pedestal_black.webp
  public/asserts/mac/pedestal_white.webp
  public/asserts/mac/support-pedestal-black.webp
  public/asserts/mac/support-pedestal-white.webp
  public/asserts/mac/support_black.webp
  public/asserts/mac/support_white.webp
  src/pages/mac.html
Labels: :lipstick:UI Improvement, ✔️Done

#146 :sparkles: feat: clock-widget-program UI 구현
  src/style.css
  src/ts/widget-manager.ts
Labels: ✨Feature, ✔️Done

#149 :sparkles: feat: icon을 추가하는 icon을 icon-bar에 추가
  public/asserts/mac/add-icon.svg
  src/ts/icon-bar.ts
  src/ts/mac-setting.ts
Labels: ✨Feature, 🔨In Progress

#148 :sparkles: feat: mac 라이트모드 / 다크모드 수동 전환 버튼 생성 및 기능 구현
  public/asserts/mac/background-web/bg-black.webp
  public/asserts/mac/background-web/bg-white.jpg
  public/asserts/mac/background-web/bg-white.webp
  public/asserts/mac/stand.webp
  public/asserts/mac/stand_longer.webp
  src/pages/doodi-all.html
  src/pages/mac.html
  src/style.css
  src/ts/button-mode-change.ts
Labels: ✨Feature, ✔️Done

#151 :lion: chore: mac 색 모드 변경 애니메이션 추가
  src/ts/button-mode-change.ts
Labels: ✔️Done, :whale:Chore

#154 :sparkles: feat: 각 게임 이름 안내 문구 추가
  src/ts/mac-setting.ts
Labels: ✨Feature, ✔️Done

#157 :sparkles: feat: context-menu의 클릭이벤트가 동작하도록 mouseup event로 기능 구현
  src/ts/context-menu.ts
Labels: ✨Feature, ✔️Done

#162 :sparkles: feat: 타이머 기능 구현
  src/ts/widget-manager.ts
Labels: ✨Feature, ✔️Done

#166 :lipstick: style: 타이머 사이즈 수정
  src/ts/widget-manager.ts
Labels: :lipstick:UI Improvement, ✔️Done

#164 :sparkles: feat: 배경화면 변경 기능 구현
  public/asserts/bg-selector-img/mac-screen-base-background-img.png
  public/asserts/bg-selector-img/mac-screen-base-dark-background-img.png
  src/pages/mac.html
  src/style.css
  src/ts/bg-selector.ts
  src/ts/context-menu.ts
Labels: ✨Feature, ✔️Done

#168 :sparkles: feat: add-icon 버튼을 클릭하면 icon이 추가되는 기능 구현
  src/programID.ts
  src/style.css
  src/ts/add-icon-setting.ts
  src/ts/icon-bar.ts
  src/ts/mac-panel-container.ts
Labels: ✨Feature, ✔️Done

#172 :bug: fix: widget에 마우스를 올렸다가 뺐을 때 부자연스러운 현상 수정
  src/style.css
Labels: 🐛Bugfix, ✔️Done

#174 :white_check_mark: test: dev에서만 필요한 버튼 추가하는 코드 비활성화
  src/ts/mac-setting.ts
Labels: ✔️Done, ✅Test

#175 :lion: chore: mac-favicon 수정, 배경에 mention 이미지와 효과음 추가, socks-game 이미지…
  public/asserts/mac/apple-logo-bite-b.webp
  public/asserts/mac/apple-logo-bite-w.webp
  public/asserts/mac/background-web/bg-black.webp
  public/asserts/mac/background-web/bg-white.webp
  public/asserts/mac/effect_switch.mp3
  src/pages/mac.html
  src/pages/socks-game.html
  src/ts/button-mode-change.ts
Labels: :lipstick:UI Improvement, ✔️Done

#177 :lion: chore: index.html의 마크업을 mac.html로 교체
  index.html
  src/ts/context-menu.ts
Labels: ✔️Done, :whale:Chore

#181 Bugfix/add icon
  src/style.css
  src/ts/add-icon-setting.ts
Labels: 🚒Hotfix, ✔️Done

#187 :lion: chore: lang 변경 작업
  src/components/calendar-widget.html
  src/components/mac-panel.html
  src/components/memo-widget.html
Labels: ✔️Done, :whale:Chore

#188 Chore/color mode
  public/asserts/mac/powerOff.mp3
  public/asserts/mac/startUp.mp3
  public/asserts/mac/timer.mp3
  src/pages/mac.html
  src/ts/button-mode-change.ts
  src/ts/mac-power-button.ts
  src/ts/widget-manager.ts
Labels: ✔️Done, :whale:Chore

#190 :lipstick: style: 포스트잇 위치, 애니메이션 수정
  index.html
  src/pages/mac.html
  src/ts/mac-setting.ts
Labels: :lipstick:UI Improvement, ✔️Done

#191 :memo: docs: Update README.md
  README.md
Labels: 📚Documentation

#192 :memo: docs: Update README.md
  README.md
Labels: 📚Documentation, ✔️Done

#194 :sparkles: feat: 발표 자료 준비
  src/pages/presentation.html
  src/ts/mac-panel-container.ts
  src/ts/widget-manager.ts
  vite.config.js
Labels: 📚Documentation, ✨Feature

#195 3차 배포
  README.md
  index.html
  public/asserts/mac/powerOff.mp3
  public/asserts/mac/startUp.mp3
  public/asserts/mac/timer.mp3
  src/components/calendar-widget.html
  src/components/mac-panel.html
  src/components/memo-widget.html
  src/pages/mac.html
  src/pages/presentation.html
  src/style.css
  src/ts/add-icon-setting.ts
  src/ts/button-mode-change.ts
  src/ts/context-menu.ts
  src/ts/mac-panel-container.ts
  src/ts/mac-power-button.ts
  src/ts/mac-setting.ts
  src/ts/widget-manager.ts
  vite.config.js
Labels: :rocket: deploy

#197 발표 준비 완료
  index.html
  src/ts/mac-setting.ts
  src/ts/widget-manager.ts
Labels: ✨Feature, ✔️Done

#198 4차 배포
  index.html
  src/ts/mac-setting.ts
  src/ts/widget-manager.ts
Labels: :rocket: deploy
